name: Schematics CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install TypeScript globally
        run: npm install -g typescript
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli
      - name: npm install, build, test
        run: |
          npm ci
          npm run build --if-present
          npm run build:test --if-present
          npm run test:unit
          npm run build:clean:add
      - name: npm install, build, test fir v12 angular app
        run: |
          npm ci
          npm run build --if-present
          npm run build:clean:add:v12
        env:
          CI: true
